version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy # Wait for the healthcheck to pass
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/ecofinds

  db:
    image: postgres:14
    volumes:
      - ./server/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecofinds
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ecofinds"]
      interval: 5s
      timeout: 5s
      retries: 5